### ISSUE TITLE
Apps built for website using self-signed SSL only show white screen

### ISSUE THREAD

**Issue by staticwave** [nativefier/nativefier#69]
I tried this with several subdomains I have which use self-signed SSL certificates and none will load within the app. I don't get an 'add exception' screen or anything, the app just loads a blank screen and stays that way.

Would be great to have an option to allow the use of self-signed certificates.

**Comment by Jeoffreybauvin** [comment]
Same for me.

**Comment by jiahaog** [comment]
Hi, is there a website or something that I can test this on? It might be possible to pass an argument to chromium as per https://discuss.atom.io/t/trusting-a-self-signed-certificate/12332

**Comment by Jeoffreybauvin** [comment]
Hi @jiahaog 

Yes, any site with a self signed certificate. For example : 

```
jeo@brs:~$ nativefier --app-name "TestSSL"  "https://lacoloc.fr"
Packaging app for platform linux x64 using electron v0.36.4
App built to /home/jeo/TestSSL-linux-x64
jeo@brs:~$ ./T
Téléchargements/   TestSSL-linux-x64/ 
jeo@brs:~$ ./TestSSL-linux-x64/TestSSL 
jeo@brs:~$ 
```

Give me a blank app.

**Comment by MiTeePingWin** [comment]
I's also seeing this problem with self-signed certs, blank apps.

**Comment by jiahaog** [comment]
This should be fixed in the next release of nativefier, I've tested it on `https://lacoloc.fr` and it seems to work fine.

**Comment by staticwave** [comment]
@jiahaog Thanks!

**Comment by Jeoffreybauvin** [comment]
It's working fine in 6.6.2 !

**Comment by AnrietteC** [comment]
I can still see a blank page for the above "https://lacoloc.fr" URL on Ubuntu 16.04 x64, Nativefier 7.3.1, Electron 1.1.3. Do I need to update anything else?

**Comment by ronjouch** [comment]
> I can still see a blank page for the above https://lacoloc.fr` URL on Ubuntu 16.04 x64, Nativefier 7.3.1, Electron 1.6.7. Do I need to update anything else?

@AnrieetteC no, same here, it's a regression. Re-opening the issue.

**Comment by AnrietteC** [comment]
Any word on this bug?

**Comment by dbeltman** [comment]
+1, This gives me a blank page on my proxmox admin page with console error: net::ERR_INSECURE_RESPONSE

**Comment by gembutterfly** [comment]
same problem here, Dynamic DNS Service which links to my raspberry.

**Comment by NiTRoeSE** [comment]
Same problem here..Website with self signed cert and all i get is a blank page.
Is there any way to fix this ?

**Comment by Yopai** [comment]
Same problem with a certificate who has expired.

**Comment by blechinger** [comment]
Since this is still open, and I found this thread while trying to find a workaround for this exact issue, checking out `nativefier --help` helped. ;)

Try building like so: `nativefier --name 'Name of App' 'AppUrl.com' --insecure --ignore-certificate`
You may want to attempt only `--ignore-certificate` and see if that suites your needs first.
This allows us to ignore the fact that the self-signed cert is insecure and load the web page anyway. I've found this quite useful for creating apps around internal web GUIs without fussing over a CA.

I would only advise using these options if the target URL is within your local network (and you're reasonably certain your local network is secure)!

Given the above is it possible this behavior is not a bug but a feature? Secure by default is certainly the way to go.

**Comment by TheCleric** [comment]
I think @blechinger 's advice is correct here and will be closing.

**Comment by rightsaidfred99** [comment]
Do these flags still work? 

Still getting a blank scree but it's fine via safari
